[tool.ruff.lint]
select = ["ALL", "PLR1702"]
exclude = ["checklists/migrations/**"]
ignore = [
    "ISC001",  # Checks for implicitly concatenated strings on a single line. @NilsIseke: Ignored on purpose as it may cause conflicts with formatter
    "COM812",  # Checks for the absence of trailing commas. @NilsIseke: Ignored on purpose as it may cause conflicts with formatter
    "TC002", "TC003",  # @kaiszuttorphilips wants to ignore this: typing-only-third-party-import, typing-only-standard-library-import
    "S311",  # Non-cryptographic random generator
    "S101",  # Checks for uses of the assert keyword.
    "D100",  # Checks for undocumented public module definitions. # Ignored because it is flagging system dependencies.
    "D101",  # Missing docstring in public class
    "D102",  # Missing docstring in public method
    "D103",  # Missing docstring in internal method
    "D104",  # Missing docstring in special method
    "D105",  # Missing docstring in magic method
    "D106",  # Missing docstring in function
    "D205",  # 1 blank line required between summary line and description
    "D400",  # Checks for docstrings in which the first line does not end in a period.
    "D401",  # First line of docstring should be in imperative mood
    "D404",  # First word of docstring should be in imperative mood
    "E501",  # Line length. We have ruff-format (ruff-format seems not to work on # comments) @NilsIseke did not find an autofix for this, therefore ignoring.
    "FA102", # We assume to use Python versions >= 3.10
    "S301", # We only load stuff that we wrap ourselves
    "PLR0913", # We just need many args...
]
[tool.mypy]
[[tool.mypy.overrides]]
module = ["sbi.*", "simglucose.*", "pathos.*","sklearn.*"]
ignore_missing_imports = true
